# Homework

Set up the environment
You need to install Python, NumPy, Pandas, Matplotlib and Seaborn. For that, you can the instructions from 06-environment.md.

# Question 1:
What's the version of Pandas that you installed?

You can get the version information using the __version__ field:

In [26]:
import pandas as pd 
pd.__version__

'2.0.3'

# Getting the data
For this homework, we'll use the California Housing Prices dataset. Download it from here.

You can do it with wget:

```wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv```

Or just open it with your browser and click "Save as...".

Now read it with Pandas.

In [27]:
df = pd.read_csv('california_housing_prices.csv')

In [28]:
df.head(2)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY

# Question 2
How many columns are in the dataset?

In [29]:
len(df.columns)

10

# Question 3
Which columns in the dataset have missing values?

In [30]:
import numpy as np
missing_data_columns = []

for col in df.columns.tolist():
    df_n = df[df[col].isin([None, '', np.nan, 'nan'])]
    if df_n.empty:
        pass
    else:
        missing_data_columns.append(col)

In [31]:
missing_data_columns

['total_bedrooms']

# Question 4
How many unique values does the ocean_proximity column have?

In [32]:
df['ocean_proximity'].drop_duplicates()

0         NEAR BAY
701      <1H OCEAN
954         INLAND
1850    NEAR OCEAN
8314        ISLAND
Name: ocean_proximity, dtype: object

In [33]:
len(df['ocean_proximity'].drop_duplicates())

5

# Question 5
What's the average value of the median_house_value for the houses located near the bay?

In [34]:
df[df['ocean_proximity'].str.upper() == 'NEAR BAY']['median_house_value'].mean()

259212.31179039303

# Question 6
Calculate the average of total_bedrooms column in the dataset.
Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.
Now, calculate the average of total_bedrooms again.
Has it changed?
Has it changed?

In [35]:
mean_value = np.round(df['total_bedrooms'].mean(), 3)

In [36]:
mean_value

537.871

In [37]:
df['total_bedrooms'] = df['total_bedrooms'].fillna(mean_value)

In [38]:
new_mean_value = np.round(df['total_bedrooms'].mean(), 3)

In [39]:
new_mean_value

537.871

# Question 7
1) Select all the options located on islands.
2) Select only columns housing_median_age, total_rooms, total_bedrooms.
3) Get the underlying NumPy array. Let's call it X.
4) Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
5) Compute the inverse of XTX.
6) Create an array y with values [950, 1300, 800, 1000, 1300].
7) Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

What's the value of the last element of w?

In [40]:
df_new = df[df['ocean_proximity'].str.upper() == 'ISLAND'][['housing_median_age', 'total_rooms', 'total_bedrooms']]

In [41]:
X = df_new.to_numpy()

In [42]:
df_new, X

(      housing_median_age  total_rooms  total_bedrooms
 8314                27.0       1675.0           521.0
 8315                52.0       2359.0           591.0
 8316                52.0       2127.0           512.0
 8317                52.0        996.0           264.0
 8318                29.0        716.0           214.0,
 array([[  27., 1675.,  521.],
        [  52., 2359.,  591.],
        [  52., 2127.,  512.],
        [  52.,  996.,  264.],
        [  29.,  716.,  214.]]))

In [43]:
XTX = (X.T).dot(X)

In [44]:
X, XTX

(array([[  27., 1675.,  521.],
        [  52., 2359.,  591.],
        [  52., 2127.,  512.],
        [  52.,  996.,  264.],
        [  29.,  716.,  214.]]),
 array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
        [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
        [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]]))

In [45]:
XTX_inv = np.linalg.inv(XTX)

In [46]:
y = np.array([950, 1300, 800, 1000, 1300])

In [47]:
XTX_inv, X.T

(array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
        [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
        [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]]),
 array([[  27.,   52.,   52.,   52.,   29.],
        [1675., 2359., 2127.,  996.,  716.],
        [ 521.,  591.,  512.,  264.,  214.]]))

In [48]:
w1 = ((XTX_inv).dot(X.T))

In [49]:
w = w1.dot(y)

In [50]:
w

array([23.12330961, -1.48124183,  5.69922946])